import pandas as pd
fastag = pd.read_csv(r'C:\Users\HP\Documents\Raaho\fasttag\data\fastag_export_1.csv')
fastag["transaction_date_time"] = pd.to_datetime(fastag["transaction_date_time"])
fastag_sorted = fastag.drop_duplicates(subset=['vehicle_reg_no'], keep='first')
direction_list = fastag.groupby('vehicle_reg_no')['lane_direction'].agg(list).reset_index()
latest_records = fastag_sorted.merge(direction_list.rename(columns={'lane_direction': 'direction_list'}), on='vehicle_reg_no', how='left')
print(f"latest_records shape: {latest_records.shape}")
print(f"latest_records missing values: {latest_records.isna().sum().to_dict()}")
vehicles = pd.read_csv(r'C:\Users\HP\Documents\Raaho\fasttag\data\suppliers_vehicles.csv')
fav_lane = pd.read_csv(r'C:\Users\HP\Documents\Raaho\fasttag\data\suppliers_favlanes.csv')
vehicles['owner_uuid'] = vehicles['owner_uuid'].astype(str).str.strip().str.upper()
fav_lane['suppliercompany_uuid'] = fav_lane['suppliercompany_uuid'].astype(str).str.strip().str.upper()
supplier_fav_lanes_data = fav_lane.merge(vehicles, left_on='suppliercompany_uuid', right_on='owner_uuid', how='left')
print(f"supplier_fav_lanes_data shape: {supplier_fav_lanes_data.shape}")
print(f"supplier_fav_lanes_data missing values: {supplier_fav_lanes_data.isna().sum().to_dict()}")
with_lanes = supplier_fav_lanes_data.merge(latest_records, left_on='reg_no', right_on='vehicle_reg_no', how='left')
print(f"with_lanes shape: {with_lanes.shape}")
print(f"with_lanes missing values: {with_lanes.isna().sum().to_dict()}")
scoring_fav_lane_level = with_lanes.loc[with_lanes.groupby('vehicle_reg_no')['transaction_date_time'].idxmax()].copy()
print(f"scoring_fav_lane_level shape: {scoring_fav_lane_level.shape}")
print(f"scoring_fav_lane_level missing values: {scoring_fav_lane_level.isna().sum().to_dict()}")
scoring_fav_lane_level['Toll_LAT'] = scoring_fav_lane_level['toll_plaza_geocode'].apply(
    lambda x: float(x.split(',')[0]) if pd.notna(x) and ',' in x else 0.0)
scoring_fav_lane_level['Toll_LON'] = scoring_fav_lane_level['toll_plaza_geocode'].apply(
    lambda x: float(x.split(',')[-1]) if pd.notna(x) and ',' in x else 0.0)
print(f"Shape after adding Toll_LAT/LON: {scoring_fav_lane_level.shape}")
print(f"Missing values after Toll_LAT/LON: {scoring_fav_lane_level.isna().sum().to_dict()}")
scoring_fav_lane_level.dropna(inplace=True)
print(f"Shape after dropna: {scoring_fav_lane_level.shape}")
print(scoring_fav_lane_level[['reg_no', 'toll_plaza_geocode', 'Toll_LAT', 'Toll_LON']].head())
